# Generated by Django 4.1.6 on 2023-02-14 14:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(default='', upload_to='media/')),
                ('likes', models.JSONField(blank=True, default=dict)),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=[], size=None)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
