# Generated by Django 4.1.6 on 2023-02-15 19:26

import authuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_alter_user_picturepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picturePath',
            field=models.ImageField(blank=True, default='', upload_to=authuser.models.upload_path),
        ),
    ]
